DROP TABLE EMPLOYEE;
DROP TABLE LEAVES;
DROP TABLE SOFT_LOANS;
DROP TABLE ADVANCE_LOANS;
DROP TABLE DEPARTMENT;
DROP TABLE PROJECT;
DROP TABLE WORKS_ON;
DROP TABLE RETIREMENT_ACCOUNT;
DROP TABLE MEMBERSHIP;
DROP TABLE WELFARE_CLUBS;
DROP TABLE HEALTHCARE_INSURANCE;
DROP TABLE HOLIDAY_CALENDAR;
DROP TABLE TAX;
DROP TABLE TAX_SLAB;
DROP TABLE SALARY_COMPONENTS;
DROP TABLE PAYROLL_PAYMENTS;



CREATE OR REPLACE TRIGGER CHECK_COUNTRY_BEFORE_INSERT
BEFORE INSERT
ON EMPLOYEE FOR EACH ROW
DECLARE
CURSOR C1 IS SELECT DISTINCT(COUNTRY) FROM HOLIDAY_CALENDAR;
V_FLAG NUMBER(1) :=0;
V_COUNTRY HOLIDAY_CALENDAR.COUNTRY%TYPE;
BEGIN
V_COUNTRY:= :new.country;

  FOR TEMP IN C1
  LOOP
        IF TEMP.COUNTRY=V_COUNTRY THEN
        V_FLAG:=1;
        END IF;
  END LOOP;
        IF(V_FLAG=0) THEN
          RAISE_APPLICATION_ERROR(-20001, 'Country not specified properly! Please check');
        END IF;
END;

CREATE TABLE EMPLOYEE(EMP_ID NUMBER(10) CONSTRAINT EMP_PK PRIMARY KEY,FNAME VARCHAR2(20) CONSTRAINT FNAME_NN NOT NULL,MINIT VARCHAR2(20),LNAME VARCHAR2(20),DOJ DATE CONSTRAINT DOJ_NN NOT NULL,DOB DATE CONSTRAINT DOB_NN NOT NULL,VPF_OPTED CHAR DEFAULT 'Y',ADDRESS VARCHAR2(50),PHONE NUMBER(12),EMAIL VARCHAR2(30),SSN NUMBER(9) CONSTRAINT SSN_NN NOT NULL, BLOOD_GROUP VARCHAR2(2),EMPLOYMENT_STATUS VARCHAR2(10) DEFAULT 'ACTIVE',DEPT_ID NUMBER(10),PLAN_ID NUMBER(10),COUNTRY VARCHAR2(20) ,CONSTRAINT EMP_HEA_FK FOREIGN KEY (PLAN_ID) REFERENCES HEALTHCARE_INSURANCE(PLAN_ID) ON DELETE CASCADE, CONSTRAINT EMP_DEP_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE,STAGE_CODE NUMBER(2),DESIGNATION VARCHAR2(20),CONSTRAINT EMP_SAL_FK FOREIGN KEY (STAGE_CODE,DESIGNATION) REFERENCES SALARY_COMPONENTS(STAGE_CODE,DESIGNATION) ON DELETE CASCADE); 

CREATE TABLE LEAVES(EMP_ID NUMBER(10),EL NUMBER(3),CL NUMBER(3),LOP NUMBER(3),CONSTRAINT LEA_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE);

CREATE TABLE SOFT_LOANS(LOAN_ID NUMBER(10) CONSTRAINT SOF_PK PRIMARY KEY,EMP_ID NUMBER(10), LOAN_AMOUNT NUMBER(10), CURRENT_BALANCE NUMBER(10), DATE_DISBURSED DATE, DUE_DATE DATE,CONSTRAINT SOF_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE);

CREATE TABLE ADVANCE_LOANS(ADVANCE_ID NUMBER(10) CONSTRAINT ADV_PK PRIMARY KEY,EMP_ID NUMBER(10), YEAR NUMBER(4), MONTH NUMBER(2), DATE_DISBURSED DATE, AMOUNT NUMBER(10),CONSTRAINT ADV_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE);

CREATE TABLE DEPARTMENT(DEPT_ID NUMBER(10) CONSTRAINT DEP_PK PRIMARY KEY,DNAME VARCHAR2(20) CONSTRAINT DEPT_NN NOT NULL);

CREATE TABLE PROJECT(PID NUMBER(10) CONSTRAINT PRO_PK PRIMARY KEY,PNAME VARCHAR2(20) CONSTRAINT PRO_NN NOT NULL, MONTHLY_INCENTIVE NUMBER(10) CONSTRAINT PROJ_MI_NN NOT NULL);

CREATE TABLE WORKS_ON(PID NUMBER(10),EMP_ID NUMBER(10),CONSTRAINT WOR_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE,CONSTRAINT WOR_PRO_FK FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE);

CREATE TABLE RETIREMENT_ACCOUNT(EMP_ID NUMBER(10) CONSTRAINT RET_NN PRIMARY KEY,PENSION_BALANCE NUMBER(10),PF_BALANCE NUMBER(10),VPF_BALANCE NUMBER(10),CONSTRAINT RET_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE);

CREATE TABLE WELFARE_CLUBS(CLUB_ID NUMBER(10) CONSTRAINT WEL_PK PRIMARY KEY, CLUB_NAME VARCHAR2(30), MONTHLY_SUBSCRIPTION NUMBER(10));

CREATE TABLE MEMBERSHIP(CLUB_ID NUMBER(10),EMP_ID NUMBER(10),CONSTRAINT MEM_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE,CONSTRAINT MEM_WEL_FK FOREIGN KEY (CLUB_ID) REFERENCES WELFARE_CLUBS(CLUB_ID) ON DELETE CASCADE);

CREATE TABLE HEALTHCARE_INSURANCE(PLAN_ID NUMBER(10) CONSTRAINT HEA_PK PRIMARY KEY,PLAN_TYPE VARCHAR2(10), MONTHLY_PREMIUM NUMBER(10) CONSTRAINT HEALTH_NN NOT NULL);

CREATE TABLE HOLIDAY_CALENDAR(COUNTRY VARCHAR2(20),DATE_HOLIDAY DATE CONSTRAINT HOL_NN NOT NULL,HOLIDAY_NAME VARCHAR2(20),CONSTRAINT HOL_PK PRIMARY KEY(COUNTRY,DATE_HOLIDAY));

CREATE TABLE TAX (TAXCODE NUMBER(10) CONSTRAINT TAX_PK PRIMARY KEY, STATE_TAX NUMBER(10) CONSTRAINT TAXS_NN NOT NULL,EMPLOYMENT_TAX NUMBER(10) CONSTRAINT TAXE_NN NOT NULL);

CREATE TABLE SALARY_COMPONENTS(BASIC NUMBER(10),STAGE_CODE NUMBER(2),DESIGNATION VARCHAR2(30),INCREMENTS NUMBER(10),CONSTRAINT SAL_PK PRIMARY KEY (STAGE_CODE,DESIGNATION));

CREATE TABLE TAX_SLAB(COUNTRY VARCHAR(20),TAXCODE NUMBER(10),BASIC NUMBER(10),CONSTRAINT TAXS_PK PRIMARY KEY (TAXCODE,COUNTRY,BASIC),CONSTRAINT TAX_TAXCODE_FK FOREIGN KEY (TAXCODE) REFERENCES TAX(TAXCODE));

CREATE TABLE PAYROLL_PAYMENTS(PAYMENT_REFERNCE NUMBER(20) CONSTRAINT PAY_PK PRIMARY KEY,EMP_ID NUMBER(10),MODE_PAYMENT VARCHAR2(10),MONTH NUMBER(2),YEAR NUMBER(4),GROSSPAY NUMBER(10),NETPAY NUMBER(10),TAX NUMBER(10),CONSTRAINT PAY_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE);