CREATE OR REPLACE PROCEDURE UPDATE_LEAVE_BALANCE IS
CURSOR EXISTING_LEAVE IS 
SELECT * FROM LEAVES L FOR UPDATE;         
TEMP EXISTING_LEAVE%ROWTYPE;
MONTH NUMBER(2);

BEGIN
OPEN EXISTING_LEAVE;

SELECT EXTRACT(MONTH FROM SYSDATE) INTO MONTH FROM DUAL;

LOOP
  FETCH EXISTING_LEAVE INTO TEMP;
    EXIT WHEN EXISTING_LEAVE%NOTFOUND;
        IF (MONTH = 1) THEN
            UPDATE LEAVES SET CL=12, EL=TEMP.EL+4, LOP=0  WHERE CURRENT OF EXISTING_LEAVE;
        ELSIF (MONTH = 4 OR MONTH = 7 OR MONTH = 10 ) THEN
            UPDATE LEAVES SET EL=TEMP.EL+4  WHERE CURRENT OF EXISTING_LEAVE;
        END IF;
END LOOP;

CLOSE EXISTING_LEAVE;
COMMIT;
END;

